### PR TITLE
fix: bnusd storage migration

### PR DESCRIPTION
**Pull request by Itshyphen**
### Commit Message

```bash
fix: bnusd storage migration
```

see the [guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages) for commit messages.

### Changelog Entry

```bash
version: <log entry>
```

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)
- [ ] I have added version bump label on PR.

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by AntonAndell — CHANGES_REQUESTED** [review]
Looks good, can we rename balanced_doller to balanced_dollar.
Also why is admin here at all? lets just remove it for now if we don't need it

**Comment by Itshyphen** [comment]
> Looks good, can we rename balanced_doller to balanced_dollar. Also why is admin here at all? lets just remove it for now if we don't need it

yeah renamed, and admin also removed, but very odd, there is admin field in mint event for the stellar token, passed contract address in that

**Comment by bishalbikram** [comment]
This check `if decimal > u8::MAX.into()` seems unnecessary since `decimal` is set to `18`, which is already within the `u8` range. Removing it could simplify the code.

**Review by AntonAndell — APPROVED** [review]

**Comment by Itshyphen** [comment]
> This check `if decimal > u8::MAX.into()` seems unnecessary since `decimal` is set to `18`, which is already within the `u8` range. Removing it could simplify the code.

yeah, made change!

**Pull request merged**
